# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\client\add_contact.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 190)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 190))
        Dialog.setMaximumSize(QtCore.QSize(300, 190))
        Dialog.setStyleSheet("background-color: purple;\n"
"color: white;\n"
"font: 63 12pt \"Lucida Sans\";")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 150, 30))
        self.comboBox.setStyleSheet("background-color: white;\n"
"color: black;")
        self.comboBox.setObjectName("comboBox")
        self.btn_refresh = QtWidgets.QPushButton(Dialog)
        self.btn_refresh.setGeometry(QtCore.QRect(190, 10, 100, 30))
        self.btn_refresh.setObjectName("btn_refresh")
        self.lbl_contacts = QtWidgets.QLabel(Dialog)
        self.lbl_contacts.setGeometry(QtCore.QRect(10, 10, 150, 20))
        self.lbl_contacts.setObjectName("lbl_contacts")
        self.btn_add = QtWidgets.QPushButton(Dialog)
        self.btn_add.setGeometry(QtCore.QRect(190, 80, 100, 30))
        self.btn_add.setObjectName("btn_add")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(190, 150, 100, 30))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Contact"))
        self.btn_refresh.setText(_translate("Dialog", "Refresh"))
        self.lbl_contacts.setText(_translate("Dialog", "Choice a contact"))
        self.btn_add.setText(_translate("Dialog", "Add"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
