# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\client\remove_contact.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 130)
        Dialog.setMinimumSize(QtCore.QSize(300, 130))
        Dialog.setMaximumSize(QtCore.QSize(300, 130))
        Dialog.setBaseSize(QtCore.QSize(0, 0))
        Dialog.setStyleSheet("background-color: purple;\n"
"color: white;\n"
"font: 63 12pt \"Lucida Sans\";")
        self.lbl_del = QtWidgets.QLabel(Dialog)
        self.lbl_del.setGeometry(QtCore.QRect(10, 10, 150, 20))
        self.lbl_del.setObjectName("lbl_del")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 150, 25))
        self.comboBox.setStyleSheet("background-color: white;\n"
"color: black;")
        self.comboBox.setObjectName("comboBox")
        self.btn_del = QtWidgets.QPushButton(Dialog)
        self.btn_del.setGeometry(QtCore.QRect(190, 10, 100, 30))
        self.btn_del.setObjectName("btn_del")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(190, 90, 100, 30))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_del.setText(_translate("Dialog", "Choice a contact"))
        self.btn_del.setText(_translate("Dialog", "Delete"))
        self.btn_cancel.setText(_translate("Dialog", "Cancele"))
